package housekeeper.bd.com.housekeeper.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "BILL".
 */
public class Bill {

    private Long id;
    private Long create_time;
    private Float total_money;
    private String record_list;
    private Boolean status;

    public Bill() {
    }

    public Bill(Long id) {
        this.id = id;
    }

    public Bill(Long id, Long create_time, Float total_money, String record_list, Boolean status) {
        this.id = id;
        this.create_time = create_time;
        this.total_money = total_money;
        this.record_list = record_list;
        this.status = status;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getCreate_time() {
        return create_time;
    }

    public void setCreate_time(Long create_time) {
        this.create_time = create_time;
    }

    public Float getTotal_money() {
        return total_money;
    }

    public void setTotal_money(Float total_money) {
        this.total_money = total_money;
    }

    public String getRecord_list() {
        return record_list;
    }

    public void setRecord_list(String record_list) {
        this.record_list = record_list;
    }

    public Boolean getStatus() {
        return status;
    }

    public void setStatus(Boolean status) {
        this.status = status;
    }

}
